### ISSUE TITLE
attempted to call service  /AutoBalancerServiceROSBridge/goPos, but failed 

### ISSUE THREAD

**Issue by himlen** [start-jsk/rtmros_tutorials#123] opened 2014-11-18 12:32 UTC
HI,
I was trying to learn euslisp
after I installed ros-hydro-hrpsys-ros-bridge ros-hydro-hironx-moveit-config and rtmros_tutorials/hrpsys_ros_bridge_tutorials package
then ran the command 
rtmlaunch hrpsys_ros_bridge_tutorials samplerobot.launch 
roseus `rospack find hrpsys_ros_bridge_tutorials`/test/hrpsys-samples/samplerobot-auto-balancer.l
irteusgl$ (samplerobot-auto-balancer-init) it showed as follow and had no respond

[ WARN] [1416310765.366491069]: Advertising on topic [/robot_interface_marker_array] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310765.411915792]: /use_sim_time is TRUE, check if /clock is pusblished or not
[ WARN] [1416310766.418410903, 44.880000000]: Advertising on topic [/larm_controller/follow_joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310766.497476355, 44.885000000]: Advertising on topic [/rarm_controller/follow_joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310766.616751438, 44.895000000]: Advertising on topic [/torso_controller/follow_joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310766.704205490, 44.900000000]: Advertising on topic [/lhand_controller/follow_joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310766.770051864, 44.905000000]: Advertising on topic [/rhand_controller/follow_joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310766.844180734, 44.915000000]: Advertising on topic [/fullbody_controller/joint_trajectory_action/goal] with an empty message definition.  Some tools (e.g. rosbag) may not work correctly.
[ WARN] [1416310769.754134926, 45.125000000]: topic /larm_controller/follow_joint_trajectory_action/goal already advertised
[ WARN] [1416310769.754298132, 45.125000000]: topic /larm_controller/follow_joint_trajectory_action/cancel already advertised
[ WARN] [1416310769.755476030, 45.125000000]: topic /rarm_controller/follow_joint_trajectory_action/goal already advertised
[ WARN] [1416310769.755673735, 45.125000000]: topic /rarm_controller/follow_joint_trajectory_action/cancel already advertised
[ WARN] [1416310769.756616651, 45.125000000]: topic /torso_controller/follow_joint_trajectory_action/goal already advertised
[ WARN] [1416310769.756919015, 45.125000000]: topic /torso_controller/follow_joint_trajectory_action/cancel already advertised
[ WARN] [1416310769.758064696, 45.125000000]: topic /lhand_controller/follow_joint_trajectory_action/goal already advertised
[ WARN] [1416310769.758761934, 45.125000000]: topic /lhand_controller/follow_joint_trajectory_action/cancel already advertised
[ WARN] [1416310769.766572049, 45.125000000]: topic /rhand_controller/follow_joint_trajectory_action/goal already advertised
[ WARN] [1416310769.770559193, 45.125000000]: topic /rhand_controller/follow_joint_trajectory_action/cancel already advertised
[ WARN] [1416310769.774266212, 45.125000000]: topic fullbody_controller/joint_trajectory_action/goal already advertised
[ WARN] [1416310769.775624908, 45.125000000]: topic fullbody_controller/joint_trajectory_action/cancel already advertised

then I commented "(send *ri* :wait-interpolation)" and tried  (samplerobot-auto-balancer-demo5)
it showed 
[ERROR] [1416310830.472440417, 52.975000000]: attempted to call service  /AutoBalancerServiceROSBridge/goPos, but failed 
[ERROR] [1416310830.477214045, 52.975000000]: attempted to call service  /AutoBalancerServiceROSBridge/waitFootSteps, but failed 

how can I figure it our?
Thanks in advance!

**Comment by snozawa** [comment] 2015-08-26 05:05
Few month ago, I confirmed your problem is reproduced on travis installing hrpsys_ros_bridge from deb.

Now I checked the same program on travis and I confirmed the problem seems to be resolved.

I close this issue, but if you find the same problem, please reopen this issue.

**Closed by snozawa** 2015-08-26 05:05 UTC
